/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KycRegistry } from "./KycRegistry";
export * as factories from "./factories";
export { KycRegistry__factory } from "./factories/KycRegistry__factory";
