/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface KycRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getKycStatus" | "setKycStatus"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "KycUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getKycStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setKycStatus",
    values: [AddressLike, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getKycStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKycStatus",
    data: BytesLike
  ): Result;
}

export namespace KycUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    verifier: AddressLike,
    verified: boolean,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    verifier: string,
    verified: boolean,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    verifier: string;
    verified: boolean;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KycRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): KycRegistry;
  waitForDeployment(): Promise<this>;

  interface: KycRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getKycStatus: TypedContractMethod<
    [user: AddressLike],
    [[boolean, string, bigint]],
    "view"
  >;

  setKycStatus: TypedContractMethod<
    [user: AddressLike, verified: boolean, ipfsHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getKycStatus"
  ): TypedContractMethod<
    [user: AddressLike],
    [[boolean, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setKycStatus"
  ): TypedContractMethod<
    [user: AddressLike, verified: boolean, ipfsHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KycUpdated"
  ): TypedContractEvent<
    KycUpdatedEvent.InputTuple,
    KycUpdatedEvent.OutputTuple,
    KycUpdatedEvent.OutputObject
  >;

  filters: {
    "KycUpdated(address,address,bool,string,uint256)": TypedContractEvent<
      KycUpdatedEvent.InputTuple,
      KycUpdatedEvent.OutputTuple,
      KycUpdatedEvent.OutputObject
    >;
    KycUpdated: TypedContractEvent<
      KycUpdatedEvent.InputTuple,
      KycUpdatedEvent.OutputTuple,
      KycUpdatedEvent.OutputObject
    >;
  };
}
